apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "elastic.configMapName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

data:
  {{- $rootContext := . }}
  {{- with .Values.elasticsearch }}
  {{- if eq .roles.master "true" }}
  cluster.initial_master_nodes: {{ include "elastic.endpoints" $rootContext | quote }}
  discovery.seed_hosts: "{{ $rootContext.Release.Name }}-elasticsearch-headless"
  {{- end }}
  cluster.name: {{ include "elastic.clusterName" $rootContext | quote }}
  network.host: {{ .networkHost | quote }}
  ES_JAVA_OPTS: {{ .esJavaOpts | quote }}
  {{- range $role, $enabled := .roles }}
  node.{{ $role }}: {{ $enabled | quote }}
  {{- end }}

  {{- if .extraConfigs }}
  {{- toYaml .extraConfigs | nindent 2 }}
  {{- end }}
  {{- end }}
