kind: Service
apiVersion: v1

metadata:
  name: {{ .Release.Name }}-elasticsearch
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

spec:
  type: ClusterIP

  selector:
    {{- include "elastic.serviceLabels" . | nindent 4 }}

  ports:
  - name: http
    port: 9200
    protocol: TCP

  - name: transport
    port: 9300
    protocol: TCP
