{{- if .Values.nodeExporter.enabled -}}
apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: {{ template "prom.node.daemonSetName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "prom.node.enrichedLabels" . | nindent 4 }}

spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ template "prom.node.podName" . }}
      {{- include "prom.node.enrichedLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ template "prom.node.podName" . }}
        {{- include "prom.node.enrichedLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"

    spec:
      serviceAccountName: {{ template "prom.node.serviceAccountName" . }}
      automountServiceAccountToken: false
      containers:
        - name: {{ template "prom.node.name" . }}-container
          image: {{ template "containerName" .Values.nodeExporter.image }}
          imagePullPolicy: "{{ .Values.nodeExporter.image.pullPolicy }}"
          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
          ports:
            - name: node
              containerPort: 9100

          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly:  true
            - name: sys
              mountPath: /host/sys
              readOnly: true

          {{- if .Values.nodeExporter.image.resources }}
          resources:
            {{- toYaml .Values.nodeExporter.image.resources | nindent 12 }}
          {{- end }}
      {{- if .Values.nodeExporter.podSecurityPolicy.enabled }}
      hostNetwork: {{ .Values.nodeExporter.podSecurityPolicy.hostNetwork }}
      hostPID: {{ .Values.nodeExporter.podSecurityPolicy.hostPID }}
      {{- end }}
      {{- if .Values.nodeExporter.image.securityContext }}
      securityContext:
        {{- toYaml .Values.nodeExporter.image.securityContext | nindent 8 }}
      {{- end }}
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
{{- end -}}
