{{- if and .Values.nodeExporter.enabled .Values.rbac.create -}}
{{- if .Values.nodeExporter.podSecurityPolicy.enabled -}}
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy

metadata:
  name: {{ template "prom.node.podSecurityPolicyName" . }}
  labels:
    {{- include "prom.node.commonLabels" . | nindent 4 }}

spec:
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false

  requiredDropCapabilities:
    - ALL

  volumes:
    - 'configMap'
    - 'hostPath'
    - 'secret'

  allowedHostPaths:
    - pathPrefix: /proc
      readOnly: true
    - pathPrefix: /sys
      readOnly: true

  hostNetwork: {{ .Values.nodeExporter.podSecurityPolicy.hostNetwork }}
  hostPID: {{ .Values.nodeExporter.podSecurityPolicy.hostPID }}
  hostIPC: false

  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535

  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535

  hostPorts:
    - min: 1
      max: 65535
{{- end }}
{{- end }}
