apiVersion: v1
appVersion: "1.0"

description: A Chart for frontendbugs
name: frontendbugs
version: 0.1.1
kubeVersion: ">=v1.15.0"

keywords:
  - "SAP"
  - "vulnerability-assessment-tool"
  - "open-source"
  - "security-tools"
  - "java"
  - "python"
  - "maven"
  - "gradle"

home: https://eclipse.github.io/steady
sources:
  - https://github.com/eclipse/steady

maintainers:
  - name: "Quoc Trung HOANG"
    email: "quoc.trung.hoang@sap.com"
    url: ""

engine: gotpl
