{{- if and .Values.kubeStateMetrics.enabled .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding

metadata:
  name: {{ template "prom.kube.serviceAccountName" . }}
  labels:
    {{- include "prom.kube.commonLabels" . | nindent 4 }}

subjects:
  - kind: ServiceAccount
    name: {{ template "prom.kube.serviceAccountName" . }}
    namespace: {{ .Values.global.namespace }}

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "prom.kube.serviceAccountName" . }}
{{- end -}}
