apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: {{ include "nginx-ingress.defaultBackend.ingressName" . }}
  namespace: {{ .Values.global.coreNamespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressController.ingressClass }}

spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "nginx-ingress.defaultBackend.serviceName" . }}
              servicePort: 8080
