apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ template "deploymentName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicas }}

  selector:
    matchLabels:
      {{- include "frontendbugs.enrichedLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "frontendbugs.enrichedLabels" . | nindent 8 }}
      {{- if .Values.extraConfigs }}
      annotations:
        checksum/frontendbugs-config: {{ include (print $.Template.BasePath "/configMap.yaml") . | sha256sum }}
      {{- end }}

    spec:
      {{- if .Values.global.podPriorityClass.enabled }}
      priorityClassName: {{ template "priorityClassName" . }}
      {{- end }}
      automountServiceAccountToken: false
      containers:
        - name: {{ template "name" . }}-container
          image: {{ template "containerName" .Values.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          {{ if .Values.image.resources -}}
          resources:
            {{- toYaml .Values.image.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.debug }}
          env:
          - name: DEBUG
            value: "true"
          {{- end }}
          {{- if .Values.extraConfigs }}
          envFrom:
          - configMapRef:
              name: {{ template "envConfigMapName" . }}
          {{- end }}
          {{- if and .Values.image.livenessProbe .Values.image.livenessProbe.enabled }}
          {{- with .Values.image.livenessProbe }}
          livenessProbe:
            initialDelaySeconds: {{ .initialDelaySeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            failureThreshold: {{ .failureThreshold }}
            tcpSocket:
              port: http
          {{- end -}}
          {{- end -}}
          {{ if and .Values.image.readinessProbe .Values.image.readinessProbe.enabled }}
          {{- with .Values.image.readinessProbe }}
          readinessProbe:
            initialDelaySeconds: {{ .initialDelaySeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            failureThreshold: {{ .failureThreshold }}
            httpGet:
              path: /bugs
              port: http
          {{- end -}}
          {{- end }}
          {{ if .Values.image.securityContext }}
          securityContext:
            {{- toYaml .Values.image.securityContext | nindent 12 }}

      securityContext:
        runAsNonRoot: true
      {{- end -}}
      {{- if .Values.selfAntiAffinity }}
      affinity:
        podAntiAffinity:
          {{- if .Values.selfAntiAffinity.soft }}
          preferredDuringSchedulingIgnoredDuringExecution:
          {{- else }}
          requiredDuringSchedulingIgnoredDuringExecution
          {{- end }}
        {{- if .Values.selfAntiAffinity.weight }}
          {{- if ge (int .Values.selfAntiAffinity.weight) 1 }}
          - weight: {{ .Values.selfAntiAffinity.weight }}
          {{- else }}
          # ERROR: .Values.selfAntiAffinity.weight < 1
          #        replaced with default value 100
          - weight: 100
          {{- end }}
        {{- else }}
          # ERROR: .Values.selfAntiAffinity.weight undefined
          #        replaced with default value 100
          - weight: 100
        {{- end }}
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values: [{{ template "name" . }}]
                - key: app.kubernetes.io/instance
                  operator: In
                  values: [{{ template "podName" . }}]
              topologyKey: "kubernetes.io/hostname"
    {{- end -}}
