{{- if and .Values.replicas (ge (int .Values.replicas) 2) -}}
{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget

metadata:
  name: {{ template "podDisruptionBudgetName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

spec:
  # INFO: User defined pdb in .podDisruptionBudget
  {{ toYaml .Values.podDisruptionBudget }}
  selector:
    matchLabels:
      {{- include "frontendbugs.enrichedLabels" . | nindent 6 }}
{{- end -}}
{{- else -}}
# INFO: Skipped podDisruptionBudget because replicas < 2
{{- end -}}
