{{- if .Values.persistentVolume -}}
{{- if .Values.persistentVolume.nfs -}}
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ template "pvcName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

spec:
  accessModes:
    - "ReadWriteMany"

  storageClassName: ""

  resources:
    requests:
      storage: {{ .Values.persistentVolume.storage | quote }}
{{- end -}}
{{- end -}}
