{{- if .Values.global.podPriorityClass.enabled -}}
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass

metadata:
  name: {{ template "priorityClassName" . }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

{{- if .Values.podPriorityClass }}
{{- if .Values.podPriorityClass.spec }}
{{- toYaml .Values.podPriorityClass.spec | nindent 0 }}
{{- else }}
# INFO: default podPriorityClass
globalDefault: false
value: 10000
preemptionPolicy: PreemptLowerPriority
description: "Specific priority for {{ template "podName" . }} with preemption"
{{- end -}}
{{- end -}}
{{- end -}}
