{{- if and .Values.rbac .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role

metadata:
  name: {{ template "restbackend.roleName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - list
      - describe

  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - describe
    resourceNames:
      - {{ .Values.global.namespace }}
{{- end -}}
