apiVersion: v1
kind: Secret

metadata:
  name: {{ template "secretName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

data:
  {{- with .Values.global.dbCredentials }}
  spring.datasource.username: {{ .postgres_user | b64enc | quote }}
  spring.datasource.password: {{ .postgres_password | b64enc | quote }}
  PGDATABASE: {{ .postgres_db | b64enc }}
  FLYWAY_USER: {{ .postgres_user | b64enc }}
  FLYWAY_PASSWORD: {{ .postgres_password | b64enc }}
  {{- end }}
