{{- if and .Values.replicas (ge (int .Values.replicas) 2) -}}
{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget

metadata:
  name: {{ template "podDisruptionBudgetName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

spec:
  {{- toYaml .Values.podDisruptionBudget | nindent 2 }}
  selector:
    matchLabels:
      {{- include "restlibutils.enrichedLabels" . | nindent 6 }}
{{- else -}}
# INFO: Skipped podDisruptionBudget = null
{{- end -}}
{{- else -}}
# INFO: Skipped podDisruptionBudget because replicas < 2
{{- end -}}
