apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: default-backend
  labels:
    component: default-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      component: default-backend
  template:
    metadata:
      labels:
        component: default-backend
    spec:
      containers:
        - name: default-backend
          image: gcr.io/google_containers/defaultbackend:1.4
          ports:
          - containerPort: 8080
          resources:
            limits:
              memory: "64Mi"
              cpu: "50m"