apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-bugs
  labels:
    component: frontend-bugs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: frontend-bugs
    spec:
      containers:
        - name: frontend-bugs
          image: eclipse/steady-frontend-bugs:3.2.0-SNAPSHOT
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"

