apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rest-lib-utils
  labels:
    component: rest-lib-utils
spec:
  replicas: 2
  template:
    metadata:
      labels:
        component: rest-lib-utils
    spec:
      containers:
        - name: rest-lib-utils
          image: eclipse/steady-rest-lib-utils:3.2.0-SNAPSHOT
          ports:
            - containerPort: 8092
          resources:
            limits:
              memory: "8Gi"
              cpu: "800m"
