apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ template "prom.server.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
