{{- if .Values.global.podPriorityClass.enabled -}}
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass

metadata:
  name: {{ template "priorityClassName" . }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

{{- if .Values.podPriorityClass }}
{{- if .Values.podPriorityClass.spec }}
# INFO: user defined ppc in .podPriorityClass.spec
{{- toYaml .Values.podPriorityClass.spec | nindent 0 }}
{{- else }}
# INFO: default podPriorityClass
globalDefault: false
value: 200
preemptionPolicy: Never
description: "Specific priority for {{ template "podName" . }}"
{{- end -}}
{{- end -}}
{{- end -}}
