apiVersion: v1
kind: Service

metadata:
  name: {{ .Release.Name }}-frontend-apps
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

spec:
  type: ClusterIP

  selector:
    {{- include "frontendapps.serviceLabels" . | nindent 4 }}

  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
