{{- if and .Values.rbac.create (not .Values.rbac.namespaced) }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: {{ template "clusterRoleName" . }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

rules: []
{{- end }}
