apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ template "configMapName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

data:
  {{- $subPath := .Values.global.subPath }}
  GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s:%(http_port)s{{ $subPath }}/monitoring/grafana"
  GF_SESSION_COOKIE_SECURE: "false"
  GF_ANALYTICS_REPORTING_ENABLED: "false"
  GF_LOG_LEVEL: "error"

  datasource.yaml: |
    apiVersion: 1

    datasources:
    - name: Prometheus
      type: prometheus
      url: http://{{ .Release.Name }}-prometheus:9090{{ $subPath }}/monitoring/prometheus
      access: proxy
      basicAuth: false
