{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding

metadata:
  name: {{ template "grafana.roleBindingName" . }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

subjects:
- kind: ServiceAccount
  name: {{ template "grafana.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}

roleRef:
  kind: Role
  name: {{ template "grafana.roleName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
