debug: false
image:
  pullPolicy: "IfNotPresent"
  registry: {}
  registryPort: {}
  name: "fluent/fluentd-kubernetes-daemonset"
  # overal resource strain with Image size: 113.02MB
  tag: "v1.7-debian-elasticsearch6-1"

resources:
  limits:
    memory: "200Mi"
    cpu: "200m"
  requests:
    memory: "150Mi"
    cpu: "150m"

metricsIndex: "fluentd"
