{{- if .Values.benchmark -}}
apiVersion: batch/v1
kind: Job

metadata:
  name: bench-pgbench-pgpool
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: pgbench
    app.kubernetes.io/instance: pgpool
    app.kubernetes.io/part-of: {{ .Values.global.projectName }}
    {{ .Values.global.projectName }}/release-name: {{ .Release.Name }}

spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pgbench
        app.kubernetes.io/instance: pgpool
        app.kubernetes.io/part-of: {{ .Values.global.projectName }}
        {{ .Values.global.projectName }}/release-name: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
        - name: bench-pgbench-pgpool
          image: postgres:11.5-alpine
          imagePullPolicy: "IfNotPresent"
          command:
            - sh
            - -c
            - |
              #!/bin/sh
              export PGPASSWORD={{ .Values.global.dbCredentials.pool_password }}
              pgbench -d -c 80 -j 8 -U {{ .Values.global.dbCredentials.pool_user }} \
                      -f /bench.sql -r -n -T 600 -h {{ .Release.Name }}-db-pool \
                      -p 5432 {{ .Values.global.dbCredentials.postgres_db }}

          volumeMounts:
          - name: bench-pgbench-sql
            mountPath: /bench.sql
            subPath: bench.sql

      volumes:
      - name: bench-pgbench-sql
        configMap:
          name: bench-pgbench-sql
{{- end -}}
