apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole

metadata:
  name: {{ template "fluentd.clusterRoleName" . }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs: ["get", "list", "watch"]
