apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: {{ include "daemonSetName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ template "podName" . }}
      {{- include "commonLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ template "podName" . }}
        {{- include "commonLabels" . | nindent 8 }}

    spec:
      serviceAccountName: {{ template "fluentd.serviceAccountName" . }}
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: minikube
          hostPath:
            path: /mnt/sda1/var/lib/docker/containers

      containers:
      - name: {{ template "name" . }}-kubernetes-container
        image: {{ template "containerName" .Values.image }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        ports:
          - name: metrics
            containerPort: 2020

        env:
          - name: PROJECT_NAME
            value: {{ .Values.global.projectName }}

          - name: NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName

          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace

          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP

          {{- if not .Values.debug }}
          - name: FLUENT_OPTS
            value: "-q"
          {{- end }}
          - name: FLUENT_UID
            value: "0"
          - name: FLUENT_ELASTICSEARCH_HOST
            value: {{ .Release.Name }}-elasticsearch
          - name: FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
          - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
            value: "true"
          - name: ELASTICSEARCH_METRICS_INDEX
            value: {{ .Values.metricsIndex | default "fluentd" | quote }}

        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: minikube
          mountPath: /mnt/sda1/var/lib/docker/containers
          readOnly: true

        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
