apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ template "fluentd.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
