apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ template "configMapName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

data:
  ssl-redirect: "false"
  {{- if .Values.ingressController.debugLevel }}
  error-log-level: "{{ .Values.ingressController.debugLevel }}"
  {{- end }}
  upstream-keepalive-timeout: "300"
  upstream-keepalive-requests: "100000"
  max-worker-connections: "100000"
  client-body-buffer-size: "128k"
  client-header-buffer-size: "1m"
  large-client-header-buffers: "4 4k"
  proxy-body-size: "100000M"
  proxy-read-timeout: "3600"
  proxy-send-timeout: "3600"
  disable-access-log: "true"
  enable-owasp-modsecurity-crs: "true"

  http-snippet: |
    {{- with .Values.ingressController }}
    {{- if .persistentVolume }}
    {{- if .persistentVolume.cache }}
    {{- if .persistentVolume.cache.enabled }}
    proxy_cache_path {{ .persistentVolume.mountPath }} levels=1:2 keys_zone=STATIC:20m max_size={{ .persistentVolume.storageG }} inactive=10d use_temp_path=off;
    {{ else }}
    proxy_cache_path /tmp/nginx-cache" levels=1:2 keys_zone=STATIC:20m max_size={{ .persistentVolume.storageG }} inactive=10d use_temp_path=off;
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
    # proxy_cache_methods GET POST;
