{{- if .Values.ingressController.persistentVolume }}
{{- if .Values.ingressController.persistentVolume.nfs -}}
apiVersion: v1
kind: PersistentVolume

metadata:
  name: {{ template "pvName" . }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

spec:
  accessModes:
    - "ReadWriteMany"

  capacity:
    storage: {{ .Values.ingressController.persistentVolume.storage }}

  nfs:
    server: {{ .Values.ingressController.persistentVolume.nfs.server }}
    path: {{ .Values.ingressController.persistentVolume.nfs.path }}
{{- end -}}
{{- end -}}
