global:
    dbCredentials:
        pool_user: pgpool
        pool_password: changeme
        postgres_db: vulas
        postgres_password: changeme
        postgres_user: postgres
        replication_user: replication
    env: TESTING
    existingClaim: {}
    masterReplicas: 1
    namespace: vulnerability-assessment-tool-core
    podPriorityClass:
        enabled: true
    projectName: vulnerability-assessment-tool
    slaveReplicas: 2
