apiVersion: v1
appVersion: v2.12.0
name: prometheus
version: v0.1.1

kubeVersion: ">=v1.15.0"
description: Helm Chart for prometheus server + kubestatemetrics + nodeExporter for the vulnerability-assessment-tool
keywords:
  - "SAP"
  - "vulnerability-assessment-tool"
  - "open-source"
  - "security-tools"
  - "java"
  - "python"
  - "maven"
  - "gradle"

home: https://eclipse.github.io/steady
sources:
  - https://github.com/eclipse/steady

maintainers:
  - name: "Quoc Trung HOANG"
    email: "quoc.trung.hoang@sap.com"
    url: ""

engine: gotpl
