# Suggestion : number of frontendapps replicas should
# be approximatively the amount of backend replicas
# in order to maximize uptime of the said service
replicas: 2

horizontalPodAutoScaler:
  enabled: true
  # If set to {} and .Values.horizontalPodAutoScaler.enabled=true
  # defaults to
  #   metrics:
  #   - type: Resource
  #     resource:
  #       name: cpu
  #       targetAverageUtilization: 70
  # Else set to a map that respects scheme defined in
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#horizontalpodautoscalerlist-v1-autoscaling
  spec: {}

podPriorityClass:
  # If .Values.global.podPriorityClass.enabled and spec is {}
  # defaults to
  #   globalDefault: false
  #   value: 200
  #   preemptionPolicy: Never
  spec: {}

# Sets logging level for shell scripts
debug: true
extraConfigs: {}

podNetworkPolicy:
  enabled: false
podDisruptionBudget: {}
  # Warning: this won't be applied unless the replicas
  #          values are >= 2
  # minAvailable: 1
selfAntiAffinity:
  #     You can set selfAntiAffinity to {} in order to skip
  #     all affinity declarations in the statefulset
  soft: true
  weight: 100

image:
  pullPolicy: "IfNotPresent"
  registry: {}
  registryPort: {}
  #     Jetty web server used to submit code for review
  name: "eclipse/steady-frontend-apps"
  #     Footprint:
  #     - size: 68 MB
  tag: "3.2.0-SNAPSHOT-jib"

  livenessProbe:
    enabled: true
    # Worst case scenario time of failed response before container is killed by k8s :
    # initialDelaySeconds + ((periodSeconds + timeoutSeconds) * failureThreshold)
    # = 82s ~= 1.5min
    initialDelaySeconds: 12
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 3

  readinessProbe:
    # Worst case scenario time before container is considered unready by k8s :
    # initialDelaySeconds + ((periodSeconds + timeoutSeconds) * successThreshold)
    # = 82s ~= 1.5min
    enabled: true
    #   Since this is a rather lightweight jetty server the startup time should
    #   be around ~ 12s.
    initialDelaySeconds: 12
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 2

  resources:
    limits:
      memory: "200Mi"
      cpu: "200m"
    requests:
      memory: "100Mi"
      cpu: "100m"

  securityContext:
    runAsUser: 65534
    runAsGroup: 65534
    privileged: false
    readOnlyRootFilesystem: false
    capabilities:
      drop:
      - ALL
      add:
      - SYS_TIME
      - NET_ADMIN
