apiVersion: v1
kind: Secret

metadata:
  name: {{ template "secretName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

data:
  {{- with .Values.global.dbCredentials }}
  SPRING_DATASOURCE_USERNAME: {{ .postgres_user | default "vulas" | b64enc }}
  SPRING_DATASOURCE_PASSWORD: {{ .postgres_password | default "changeme"  | b64enc }}
  PGDATABASE: {{ .postgres_db | default "vulas" | b64enc }}
  FLYWAY_USER: {{ .postgres_user | default "vulas" | b64enc }}
  FLYWAY_PASSWORD: {{ .postgres_password | default "changeme" | b64enc }}
  {{- end }}

  {{- if .Values.extraSecrets }}
  {{- toYaml .Values.extraSecrets | nindent 2 }}
  {{- end }}
