{{- if .Values.kibana.enabled -}}
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "kibana.configMapName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

data:
  ELASTICSEARCH_HOSTS: "http://{{ .Release.Name }}-elasticsearch:9200"
  SERVER_HOST: {{ .Values.kibana.serverHost | quote }}
  SERVER_REWRITEBASEPATH: "true"
  SERVER_BASEPATH: {{ .Values.global.subPath }}{{ .Values.kibana.path }}
  SERVER_NAME: "kibana"

  NODE_OPTIONS: "--max-old-space-size=2000"
  {{- if .Values.kibana.debug }}
  LOGGING_VERBOSE: "true"
  {{- else }}
  LOGGING_QUIET: "true"
  LOGGING_SILENT: "true"
  {{- end }}

  {{- if .Values.kibana.extraConfigs }}
  {{- toYaml .Values.kibana.extraConfigs | nindent 2 }}
  {{- end }}
  {{/* logtrail.json: {{ .Files.Get "files/logtrail.json" | quote }} */}}
{{- end -}}
