{{- if .Values.kibana.enabled -}}
{{- if and .Values.kibana.replicas (ge (int .Values.kibana.replicas) 2) -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget

metadata:
  name: {{ include "kibana.podDisruptionBudgetName" . }}
  namespace: {{ .Values.global.namespace }}

  labels:
    {{- include "commonLabels" . | nindent 4 }}

spec:
  {{- if .Values.kibana.podDisruptionBudget }}
  {{- toYaml .Values.kibana.podDisruptionBudget | nindent 2 }}
  {{- else }}
  minAvailable: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "kibana.enrichedLabels" . | nindent 6 }}
{{- end -}}
{{- end -}}
