kind: Service
apiVersion: v1
metadata:
  name: haproxy-ingress
  labels:
    component: haproxy-ingress
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: public-http
      port: 8080
      targetPort: http
    - name: public-https
      port: 443
      targetPort: http
    - name: public-stat
      port: 1936
      targetPort: stat
  selector:
    component: haproxy-ingress
---

