{{- if .Values.defaultBackend.enabled }}
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ template "nginx-ingress.defaultBackend.mountedConfigMapName" . }}
  namespace: {{ .Values.global.coreNamespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

data:
  nginx.conf: |-
    user  nginx;
    worker_processes  1;

    error_log               /var/log/nginx/error.log warn;
    pid                     /var/run/nginx.pid;

    events {
      worker_connections    1024;
    }

    http {
      include               /etc/nginx/mime.types;
      default_type          application/octet-stream;
      access_log            off;
      sendfile              on;
      keepalive_timeout     65;
      server {
          listen            8080;
          server_name       localhost;
          access_log        off;

          location = /healthz {
            return 200;
          }

          location ~ ^/$ {
            return 301 https://eclipse.github.io/steady;
          }

          location / {
            root   /usr/share/nginx/html;
          }
      }
    }

  browser.json: |-
    [
      {
          "text": "05 Jun 2019 – Placeholder",
          "type": "Success",
          "active": false
      },
    ]

{{- end -}}
