{{- if .Values.defaultBackend.enabled -}}
{{- if and .Values.defaultBackend.replicas (ge (int .Values.defaultBackend.replicas) 2) -}}
{{- if .Values.defaultBackend.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget

metadata:
  name: {{ template "nginx-ingress.defaultBackend.podDisruptionBudgetName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

spec:
  {{ toYaml .Values.defaultBackend.podDisruptionBudget }}
  selector:
    matchLabels:
      {{- include "nginx-ingress.defaultBackend.enrichedLabels" . | nindent 6 }}
{{- end -}}
{{- end -}}
{{- end -}}
