{{- if .Values.defaultBackend.enabled }}
apiVersion: v1
kind: Service

metadata:
  name: {{ include "nginx-ingress.defaultBackend.serviceName" . }}
  namespace: {{ .Values.global.coreNamespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

spec:
  selector:
    {{- include "nginx-ingress.defaultBackend.serviceLabels" . | nindent 4 }}

  ports:
  - name: "container"
    port: 8080
    targetPort: 8080
    protocol: TCP
{{- end -}}
